module.exports = [
	{ no: "[Gg]ithub", yes: "GitHub" },
	{ no: "[Jj]avascript", yes: "JavaScript" },
	{ no: "[Tt]ype[Ss]cript", yes: "TypeScript" },
	{ no: "[Gg]atsby\\.\?[Jj][Ss]", yes: "Gatsby" },
	{ no: "gatsby", yes: "Gatsby" },
	{ no: "[Gg]astby", yes: "Gatsby" },
	{ no: "[Rr]eact\\.\?[Jj][Ss]", yes: "React" },
	{ no: "react", yes: "React" },
	{ no: "node\\.\?[Jj][Ss]", yes: "Node.js" },
	{ no: "[Nn]ode[Jj][Ss]", yes: "Node.js" },
	{ no: "[Nn]pm\\.\?[Jj][Ss]", yes: "npm" },
	{ no: "Npm", yes: "npm" },
	{ no: "Webpack", yes: "webpack" },
	{ no: "[Ww]ord[Pp]ress", yes: "WordPress" },
]
